name: theseus
version: 2.1.0
homepage: https://github.com/DisDis/theseus
description: Theseus port https://github.com/jamis/theseus version 1.0.2. Theseus is a library for generating and solving mazes.

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.20.1
  image: ^3.1.0
