name: theseus
version: 1.0.3+2
homepage: https://github.com/DisDis/theseus
authors:
- Jamis Buck <jamis@jamisbuck.org>
- Igor Demyanov <igor.demyanov@gmail.com>
description: Theseus port https://github.com/jamis/theseus version 1.0.2. Theseus is a library for generating and solving mazes.
dev_dependencies:
  test: "^0.12.0"
  image: "^1.1.0"
